config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :characters, except: [:edit, :update]
  resources :generations, only: [:new]
  get 'generations/generate_story', to: 'generations#generate_story', as: 'generate_story'
  get 'generations/generate_sentence', to: 'generations#generate_sentence', as: 'generate_sentence'
  get '/tavern', to: 'characters#tavern', as: 'tavern'
  post 'characters/:id/share', to: 'characters#share', as: 'shared_character'
  post 'characters/:id/buy_pint', to: 'characters#buy_pint', as: 'buy_pint'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
belongs_to :user
has_many :reviews

validates :full, inclusion: { in: [true, false] }
validates :full, exclusion: { in: [nil] }
validates :name, presence: true
validates :race, presence: true
validates :job, presence: true

validates :location, presence: true, unless: :full?
validates :trait, presence: true, unless: :full?
validates :quirk, presence: true, unless: :full?

validates :alignment, presence: true, if: :full?
validates :background, presence: true, if: :full?

private

  def full?
    full
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :characters
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def default_url_options
  { host: ENV["www.characterize.site"] || "localhost:3000" }
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :destroy, :share, :buy_pint]

  def new
    @character = Character.new
    file = File.read(Rails.root.to_s + "/db/text.json")
    json = JSON.parse(file)

    @races = json["races"]
    @jobs = json["jobs"]
    @alignments = json["alignments"]
    @backgrounds = json["backgrounds"]

    @starting_words = Generator.fetch_possibilities
  end

  def create
    @character = Character.new(character_params)
    @character.photo = "characters/#{character_params[:race]}_#{character_params[:job]}.png"
    @character.rating = 0

    if current_user
      @character.user = current_user
      if @character.save!
        redirect_to characters_path
      else
        redirect_to root_path, notice: "Something went wrong, please try again"
      end
    else
      redirect_to new_user_session
    end
  end

  def show
  end

  def index
    @user = current_user
    @characters = Character.where(user: current_user)
  end

  def tavern
    @user = current_user
    @characters = Character.where(shared: true).order(rating: :desc)
  end

  def share
    if @character.shared
      redirect_to character_path(@character), alert: "This character is already at the Tavern"
    else
      @character.shared = true
      @character.save
      redirect_to tavern_path
    end
  end

  def buy_pint
    if @character.rating
      @character.rating += 1
    else
      @character.rating = 1
    end

    @character.save
    redirect_to character_path
  end

  def destroy
    @character.destroy
    redirect_to characters_path
  end

  private

  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    if params[:character] && params[:character][:trait]
      params.require(:character).permit(:name, :race, :job, :location, :trait, :quirk, :story, :alignment, :background, :personality_traits, :bond, :ideal, :flaw)
    else
      {
        :name => params[:name],
        :race => params[:race],
        :job => params[:job],
        :alignment => params[:alignment],
        :background => params[:background],
        :personality_traits => params[:personality_traits],
        :ideal => params[:ideal],
        :bond => params[:bond],
        :flaw => params[:flaw],
        :story => params[:story],
        :full => true
      }
    end
  end
end

app/controllers/generations_controller.rb
class GenerationsController < ApplicationController
  def new
    @character_params = generate_attributes
    @character = Character.new(@character_params)
    @character.photo = "characters/#{@character_params['race']}_#{@character_params['job']}.png"
    # @character.photo = "characters/#{@character_params['race']}_#{@character_params['job']}.png"
  end


  def generate_story
    suggested_words = Generator.fetch_possibilities(word: params[:word])

    response = {
      word: params[:word],
      suggestions: suggested_words
    }

    render json: response
  end

  def generate_sentence
    sentence = Generator.generate_sentence(word: params[:word])

    response = {
      word: sentence.last,
      sentence: sentence
    }

    render json: response
  end


  private

  def generate_attributes
    path = Rails.root.to_s + "/db/text.json"
    attributes = load_attributes(path)
    template = attributes[:templates].sample
    background = attributes[:backgrounds].keys.sample

    character_params = {
      'name' => attributes[:names].sample,
      'trait' => attributes[:traits].sample,
      'race' => attributes[:races].sample,
      'job' => attributes[:jobs].sample,
      'location' => attributes[:locations].sample,
      'quirk' => attributes[:quirks].sample,
      'background' => background.to_s,
      'personality_traits' => attributes[:backgrounds][background]['personality_traits'].sample(2).join(' '),
      'ideal' => attributes[:backgrounds][background]['ideal'].sample,
      'bond' => attributes[:backgrounds][background]['bond'].sample,
      'flaw' => attributes[:backgrounds][background]['flaw'].sample,
      'rating' => attributes[:rating]
    }

    character_params[:story] = template.gsub(/trait|race|job|location|quirk/) { |match| character_params[match] } + "."

    character_params
  end

  def load_attributes(file_name)
    file = File.read(file_name)
    text = JSON.parse(file)

    attributes = {
      templates: text["templates"],
      names: text["names"],
      traits: text["traits"],
      races: text["races"],
      jobs: text["jobs"],
      locations: text["locations"],
      quirks: text["quirks"],
      backgrounds: text["backgrounds"],
      rating: 0
    }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/characters/_random.html.erb
<%= render "shared/character_show" %>

app/views/characters/_stats.html.erb
<div id="character_attributes" data-character_attributes="<%= JSON.generate(@backgrounds) %>"></div>

<div class="character-build-container">
  <div class="character-build">

          <div class="character-attribute-section" id="race-selection">
            <div class="name-wrapper">
              <h1>Name</h1>
              <%= text_field_tag "name", "", id: "character-name", class:"type-name" %>
            </div>
            <h1 style="width: 100%" class="race-header">Race</h1>
            <div class="container">
              <div class="row">
                <% @races.each do |race| %>
                  <div class="col-xs-6">
                    <div class="character-choice chacter-select-btn" data-attribute="race" data-value="<%= race %>" data-parent_id="race-selection">
                      <%= radio_button_tag "race", race, id: "race-#{race}" %>
                      <%= label_tag "race-#{race}", race.capitalize %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>


          <div class="character-attribute-section" id="job-selection" style="display: none;">
            <h1 class="character-attribute-header">Class</h1>
            <div class="container">
              <div class="row">
                <% @jobs.each do |job| %>
                <div class="col-xs-6">
                  <div class="character-choice chacter-select-btn" data-attribute="job" data-value="<%= job %>" data-parent_id="job-selection">
                    <%= radio_button_tag "job", job, id: "job-#{job}" %>
                    <%= label_tag "job-#{job}", job.capitalize %>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>



          <div class="character-attribute-section" id="background-selection" style="display: none;">
            <h1 class="character-attribute-header">Background</h1>
            <div class="container">
              <div class="row">
                <% @backgrounds.keys.each do |background| %>
                  <div class="col-xs-6">
                    <div class="character-choice chacter-select-btn" data-parent_id="background-selection" data-attribute="background" data-value="<%= background %>" data-value="<%= background %>">
                      <%= radio_button_tag "background", background, id: "background-#{background}" %>
                      <%= label_tag "background-#{background}", background.capitalize %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>



          <div class="character-attribute-section" id="alignment-selection" style="display: none;">
            <h1 class="character-attribute-header">Moral Alignment</h1>
            <div class="container">
              <div class="row">
              <% @alignments.each do |alignment| %>
                <div class="col-xs-6">
                  <div class="character-choice chacter-select-btn" data-parent_id="alignment-selection" data-attribute="alignment" data-value="<%= alignment %>">
                    <%= radio_button_tag "alignment", alignment, id: "alignment-#{alignment}" %>
                    <%= label_tag "alignment-#{alignment}", alignment.capitalize %>
                  </div>
                </div>
              <% end %>
              </div>
            </div>
          </div>



          <div class="character-attribute-section" id="personality_traits-selection" data-attribute="personality_traits" style="display: none;">
            <h1 class="character-attribute-header">Personality</h1>
            <div class="container">
              <div class="row">
              </div>
            </div>
          </div>



          <div class="character-attribute-section" id="personality_traits-selection2" data-attribute="personality_traits2" style="display: none;">
            <h1 class="character-attribute-header">Personality</h1>
            <div class="container">
              <div class="row">
              </div>
            </div>
          </div>



          <div class="character-attribute-section" id="ideal-selection" style="display: none;">
            <h1 class="character-attribute-header">Ideal</h1>
            <div class="container">
              <div class="row">
              </div>
            </div>
          </div>



          <div class="character-attribute-section" id="bond-selection" style="display: none;">
            <h1 class="character-attribute-header">Bond</h1>
            <div class="container">
              <div class="row">
              </div>
            </div>
          </div>


          <div class="character-attribute-section" id="flaw-selection" style="display: none;">
            <h1 class="character-attribute-header">Flaw</h1>
            <div class="container">
              <div class="row">
              </div>
            </div>
            <button class="hidden" id="confirm">Next!</button>
          </div>
      </div>
</div>

app/views/characters/_story.html.erb
<!-- <div class="character-story-generator"> -->
  <div class="container character-story-generator">
    <div class="row">
      <div class="generation-column character-attribute-list col-xs-13 col-lg-4">

        <div class="character-summary">
          <div class="stats-card">
            <div class="stats dl">
              <dl id="attributes-list">
              </dl>
            </div>
          </div>
        </div>

      </div>
      <div class="generation-column word-selection-column col-xs-13 col-lg-4">

        <div class="sentence-generator">
          <div class="btn-group build-buttons container">
            <div class="row">
                <% @starting_words.each do |word| %>
                  <div class="random-word-button col-xs-4 col-sm-4 col-md-4">

                      <button class="btn-word word-selection" href="#"><%= word.capitalize %></button>

                  </div>
                <% end %>
                <div class="random-word-button col-xs-4 col-sm-4 col-md-4">
                  <button class="btn-word word-selection" href="#"></button>
                </div>
            </div>
          </div>
          <%= button_tag "Generate some words", class: "master-button", id:"generate-sentence"%>
        </div>

      </div>
      <div class="generation-column col-xs-13 col-lg-4 story-column">

        <div class="character-sheet">
          <div class="character-sheet-head">
            <%= image_tag "top_edge.png", class:"paper"%>
          </div>
          <div class="character-sheet-body">
            <div class="title">
              <p>Your Backstory</p>
            </div>
            <div class="story">
              <%= text_area_tag 'story', "" %>
            </div>
          </div>
          <div class="bottom-edge">
            <%= image_tag "bottom_edge.png", class:"paper bottom"%>
          </div>
          <%= button_tag "Save", class: "master-button", id:"save-story" %>
          <%= button_tag "Restart", class: "master-button", id:"restart-story" %>
        </div>

      </div>
    </div>
  </div>
<!-- </div> -->

app/views/characters/index.html.erb
<div class="index-container">
  <div class="container margin-bottom-30">
    <div class="row">
      <h1 align="center" class="index-title">My Characters</h1>
      <% @characters.each_with_index do |character| %>
        <%= link_to character_path(character) do %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="character-card">
              <%= image_tag character.photo, :class => "avatar" %>
              <div class="character-card-content">
                <div class="content-header-tavern">
                  <div class="inner-header">
                    <h4><%= character.name %></h4>
                  </div>
                </div>
                <div class="content-body-tavern">
                  <div class="character-bio">
                    <%= truncate(character.story, :length => 90) %>
                  </div>
                  <% if character.shared %>
                    <div class="pints">
                      <span><%= character.rating %><%= image_tag 'pint.png', class:"pint_icon"%></span>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/characters/new.html.erb
<div id="first-part">
  <%= render "characters/stats" %>
</div>

<div id="second-part" style="display: none">
  <%= render "characters/story" %>
</div>

<% content_for(:after_js) do %>
  <script>
  function capitalize(word) {
    return word.charAt(0).toUpperCase() + word.slice(1);
  }
  const button = document.getElementById("confirm");
  const attributesList = document.getElementById("attributes-list");
  const wordbuttons = document.querySelectorAll("button.word-selection");
  button.addEventListener("click", (event) => {
    event.preventDefault();
    if(selectedAttributes.name) {
      wordbuttons[wordbuttons.length - 1].innerText = capitalize(selectedAttributes.name);
    }
    else {
      wordbuttons[wordbuttons.length - 1].innerText = "Undefined";
    };
    document.getElementById("first-part").style.display = "none";
    document.getElementById("second-part").style.display = "initial";
    // let attributes = document.getElementById("attributes").children;
    attributesList.innerHTML =
      `<h1 class="character-name"> ${selectedAttributes.name} </h1>
      <div class="flex-std">
          <div class="card-info-content">
            <h2>Race</h2>
            <p> ${selectedAttributes.race} </p>
          </div>
          <div class="card-info-content">
            <h2>Class</h2>
            <p> ${selectedAttributes.job} </p>
          </div>
        </div>
        <div class="flex-std">
          <div class="card-info-content">
            <h2>Alignment</h2>
            <p> ${selectedAttributes.alignment} </p>
          </div>
          <div class="card-info-content">
            <h2>Background</h2>
            <p> ${selectedAttributes.background} </p>
          </div>
        </div>
      </div>
      <h2>Personality Traits</h2>
      <p> ${selectedAttributes.personality_traits} </p>
      <h2>Ideal</h2>
      <p> ${selectedAttributes.ideal} </p>
      <h2>Bond</h2>
      <p> ${selectedAttributes.bond} </p>
      <h2>Flaw</h2>
      <p> ${selectedAttributes.flaw} </p>`;
// =======
//       `
//       <h1> ${selectedAttributes.name} </h1>
//       <div class="container character-stats-container">
//         <div class="row">
//           <div class="col-xs-6">
//           <dt>Race</dt>
//             <dd> ${selectedAttributes.race} </dd>
//           </div>
//           <div class="col-xs-6">
//             <dt>Class</dt>
//             <dd> ${selectedAttributes.job} </dd>
//           </div>
//           <div class="col-xs-6">
//             <dt>Alignment</dt>
//             <dd> ${selectedAttributes.alignment} </dd>
//           </div>
//           <div class="col-xs-6">
//             <dt>Background</dt>
//             <dd> ${selectedAttributes.background} </dd>
//           </div>
//         </div>
//       </div>
//       <dt>Personality Traits</dt>
//       <dd> ${selectedAttributes.personality_traits} </dd>
//       <dt>Ideal</dt>
//       <dd> ${selectedAttributes.ideal} </dd>
//       <dt>Bond</dt>
//       <dd> ${selectedAttributes.bond} </dd>
//       <dt>Flaw</dt>
//       <dd> ${selectedAttributes.flaw} </dd>`;
// >>>>>>> master
  });
  let respond = true;
  let storyary = [];
  const story = document.getElementById("story");
  wordbuttons.forEach(function(wordbutton) {
    wordbutton.addEventListener("click", (event) => {
      var word = event.srcElement.innerText;
      if(respond) {
        respond = false;
        fetch(`<%= generate_story_path %>?word=${word}`, {
          credentials: "same-origin"
        })
        .then(response => {
          return response.json();
        })
        .then((data) => {
          respond = true
          // replace all existing word buttons with new words
          // storyary.push(data.word)
          if (data.word === "." || story.value === "") {
            story.value = story.value + data.word
          } else {
            story.value = story.value + " " + data.word
          }
          // grab array of new words
          data.suggestions.push(capitalize(attributesList.firstElementChild.innerText))
          data.suggestions.forEach(function(suggestion, index) {
            if (story.value[story.value.length - 1] === ".") {
              wordbuttons[index].innerText = capitalize(suggestion)
            } else {
              wordbuttons[index].innerText = suggestion
            }
          });
        });
      }
    });
  });
  const sentenceGenerator = document.getElementById("generate-sentence");
  sentenceGenerator.addEventListener("click", (event) => {
    let curr_word = "";
    storyary = story.value.split(' ')
    if(storyary[storyary.length - 1]) {
      curr_word = storyary[storyary.length - 1];
    }
    if(respond) {
      respond = false;
      fetch(`<%= generate_sentence_path %>?word=${curr_word}`, {
        credentials: "same-origin"
      })
      .then(response => {
        return response.json();
      })
      .then((data) => {
        respond = true;
        if(story.value[story.value.length - 1] === "." || story.value === "") {
          story.value += " " + data.sentence.replace(data.sentence[0], data.sentence[0].toUpperCase())
        }
        else {
          story.value += " " + data.sentence
        }
      });
    }
  });
  const save = document.getElementById("save-story")
  save.addEventListener("click", (event) => {
    fetch("/characters", {
      method: 'post',
      actions: 'create',
      headers:{
        'X-Requested-With': 'XMLHttpRequest',
        'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content'),
        'Content-Type': 'application/json',
      },
      credentials: 'same-origin',
      body: JSON.stringify({
        name: selectedAttributes.name,
        race: selectedAttributes.race,
        job: selectedAttributes.job,
        alignment: selectedAttributes.alignment,
        background: selectedAttributes.background,
        personality_traits: selectedAttributes.personality_traits,
        ideal: selectedAttributes.ideal,
        bond: selectedAttributes.bond,
        flaw: selectedAttributes.flaw,
        story: story.value
      })
    }).then((response) => {
      window.location = "/characters";
    });
  });
  const restart = document.getElementById("restart-story");
  restart.addEventListener("click", (event) => {
    storyary.length = 0;
    story.value = "";
    wordbuttons.forEach(function(wordbutton) {
      var word = wordbutton.innerText;
      wordbutton.innerText = word.charAt(0).toUpperCase() + word.slice(1);
    });
  });
  const edit = document.getElementById("edit-characteristics");
  edit.addEventListener("click", (event) => {
    event.preventDefault();
    location.reload();
  });
</script>
<% end   %>

app/views/characters/show.html.erb
<%= render 'characters/random' %>

app/views/characters/tavern.html.erb
<div class="index-container">
  <div class="container margin-bottom-30">
    <div class="row">
      <h1 align="center" class="index-title">The Tavern</h1>
      <% @characters.each_with_index do |character| %>
        <%= link_to character_path(character) do %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="character-card">
              <%= image_tag character.photo, :class => "avatar" %>
              <div class="character-card-content">
                <div class="content-header-tavern">
                  <div class="inner-header">
                    <h4><%= character.name %></h4>
                    <p> created by <b><%= character.user.username %></b></p>
                  </div>
                </div>
                <div class="content-body-tavern">
                  <div class="character-bio">
                    <%= truncate(character.story, :length => 90) %>
                  </div>
                  <div class="pints">
                    <span><%= character.rating %><%= image_tag 'pint.png', class:"pint_icon"%></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/generations/new.html.erb
<%= render "shared/character_show" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Italianno|Tangerine|Roboto:300,400,700" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%# meta_title %></title>
    <meta name="description" content="<%# meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%# meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%# request.original_url %>" />
    <meta property="og:image" content="<%# meta_image %>" />
    <meta property="og:description" content="<%# meta_description %>" />
    <meta property="og:site_name" content="<%# meta_title %>" />

    <% favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body style="background-color: #F7F7F7;">
    <%= render 'shared/flashes' %>
    <div id="container">
        <%= render 'shared/navbar' %>
        <%= yield %>
    </div>
    <div class="footer-container">
      <%= render 'shared/footer' %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:after_js) %>
  </body>

</html>

app/views/pages/home.html.erb
<div class="landing-background">
  <h1 class="landing-text">CHARACTERIZE</h1>
  <h2 class="landing-sub-text">BUILD YOUR BACKSTORY</h2>
  <div style="text-align: center;">
    <span class="banner-script"></span>
  </div>
  <div class='margin-top'>
    <%= link_to new_generation_path, class: "banner-buttons" do %>
      <p class="btn btn-primary">QUICK STORY</p>
    <% end %>
    <%= link_to new_character_path, class: "banner-buttons margin-left-10"  do %>
      <p class="btn btn-primary">CUSTOM STORY</p>
    <% end %>
  </div>
</div>

app/views/shared/_character_show.html.erb
<div class="car-card-wrapper">
  <div class="car-card-img-wrapper">
    <%= image_tag @character.photo, class: "image" %>
  </div>
  <div class="car-info-wrapper">
    <div class="car-info-padding">
      <div>
        <h1><%= @character.name.upcase %></h1>
        <p><%= @character.story %></p>
      </div>
      <div class="flex-std">
        <% if @character.full == true %>
        <div class="card-info-content">
          <h2>RACE, CLASS, ALIGNMENT</h2>
          <p><%= @character.race.capitalize %>, <%= @character.job.capitalize %>, <%= @character.alignment.capitalize %></p>
        </div>
        <% end %>
        <div class="card-info-content">
          <h2>MY BACKGROUND</h2>
          <p><%= @character.background %></p>
        </div>
      </div>
      <div class="flex-std">
        <div class="card-info-content">
          <h2>PERSONALITY TRAITS</h2>
          <p><%= @character.personality_traits.split('.')[0] %>. <%= @character.personality_traits.split('.')[1] %>.</p>
        </div>
        <div class="card-info-content">
          <h2>IDEAL</h2>
          <p><%= @character.ideal %></p>
        </div>
      </div>

      <div class="flex-std">
        <div class="card-info-content">
          <h2>BOND</h2>
          <p><%= @character.bond %></p>
        </div>
        <div class="card-info-content">
          <h2>FLAW</h2>
          <p><%= @character.flaw %></p></p>
        </div>
      </div>
      <% unless @character_params.nil? %>
        <%= simple_form_for @character do |f| %>
        <%= f.input :story, as: :hidden %>
        <% @character_params.each do |attribute, value| %>
          <%= f.input attribute.to_sym, as: :hidden %>
        <% end %>
        <div class= "banner-buttons margin-top">
          <%= link_to 'RANDOM AGAIN', new_generation_path, class: "btn btn-primary char-button" %>
          <%= f.button :submit, "SAVE THIS", class: "btn btn-primary char-button" %>
        </div>
        <% end %>
      <% end %>
      <div class="banner-buttons margin-top">
        <% unless @character.id.nil? %>
        <% if  @character.user == current_user  %>
          <%= link_to 'DELETE', { action: :destroy, id: @character.id }, method: :delete, class:"btn" %>
          <%= link_to 'SHARE', { action: :share, id: @character.id }, method: :post, class:"btn" %>
        <% else %>
          <%= link_to 'BUY A PINT', { action: :buy_pint, id: @character.id }, method: :post, class:"btn" %>
      <div class="rating">
        <p><%= @character.rating %></p><%= image_tag "pint.png", alt:"PINT", size: "50x50", class:"pint-icons" %>
      </div>
        <% end %>
        <% end %>
      </div>
      </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon sticky navbar-<%= action_name %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "snake.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <div class="menu-icons">
      <%= link_to characters_path, class:"icons book" do %> <%= image_tag('book.png', alt: "MY CHARACTERS", title: "MY CHARACTERS") %> <p>MY CHARACTERS</p> <% end %>
      <%= link_to new_generation_path, class:"icons dice" do %> <%= image_tag('dice.png', alt: "QUICK STORY", title: "QUICK STORY") %> <p>QUICK STORY</p><% end %>
      <%= link_to new_character_path, class:"icons quill" do %> <%=image_tag('quill_pen.png', alt: "CUSTOM STORY", title: "CUSTOM STORY") %> <p>CUSTOM STORY</p><% end %>
      <%= link_to tavern_path, class:"icons helmet" do %> <%= image_tag('tavern.png', alt: "THE TAVERN", title: "THE TAVERN") %> <p>THE TAVERN</p><% end %>
    </div>

    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path,  class: "log-out", method: :delete do %>
        <!-- <i style="color: white", class="fa fa-sign-out"></i> -->  <%= t(".sign_out", style: "color: white;",default: "Log out",) %>
      <% end %>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to characters_path, class:"icons book" do %> <%= image_tag('book.png', alt: "MY CHARACTERS", title: "MY CHARACTERS") %> MY CHARACTERS <% end %></li>
        <li> <%= link_to new_generation_path, class:"icons dice" do %> <%= image_tag('dice.png', alt: "QUICK STORY", title: "QUICK STORY") %> QUICK STORY<% end %></li>
        <li><%= link_to new_character_path, class:"icons quill" do %> <%= image_tag('quill_pen.png', alt: "CUSTOM STORY", title: "CUSTOM STORY") %> CUSTOM STORY<% end %></li>
        <li><%= link_to tavern_path, class:"icons helmet" do %> <%= image_tag('tavern.png', alt: "THE TAVERN", title: "THE TAVERN") %> MY CHARACTERS<% end %></li>
      </ul>
    </div>
  </div>
</div>